### ISSUE TITLE
Logging doesn't work on watch

### ISSUE THREAD

**Issue by SassNinja** [riot/webpack-loader#18] opened 2018-05-07 08:58 UTC
I'm using the riot-tag-loader and have enabled the watch mode in my webpack config.

```sh
$ webpack --watch --config webpack.dev.js
```

```javascript
module: {
    rules: [
        {
            test: /.tag$/,
            exclude: /node_modules/,
            use: [
                {
                    loader: 'file-loader',
                    options: {
                        name: '[name].tag.js',
                        outputPath: 'riot'
                    }
                },
                {
                    loader: 'riot-tag-loader',
                    options: {
                        hot: false,
                        compact: true,
                        modular: true,
                        type: 'es6',
                        style: 'scss'
                    }
                }
            ]
        }
    ]
}
```

Works initially correct, meaning the tags get compiled.

When I change the tag afterwards (while watched) is gets recompiled but this is not visible in the terminal!
`--info-verbosity verbose` doesn't help either.

When I change another JS file (also watched) it's visible in the terminal.
So I think the riot-tag-loader doesn't provide the necessary logging to webpack's watchmode.

Is this not supported or is there any mistake in my webpack config?

I'm using webpack 4.6.0

**Comment by GianlucaGuarini** [comment] 2019-04-19 13:37
Are you able to reproduce this issue also with the newest loader version? Could you setup a repo to check the issue please?

**Comment by GianlucaGuarini** [comment] 2019-04-30 20:04
closing this issue since no feedback was provided.

**Closed by GianlucaGuarini** 2019-04-30 20:04 UTC
Labels: question
